[Unit]
After=
After=qcom-sns-init.service
Requires=
Requires=qcom-sns-init.service
BindsTo=qcom-sns-init.service
PartOf=qcom-sns-init.service
StartLimitIntervalSec=0

[Service]
ExecStart=
ExecStart=/usr/libexec/iio-sensor-proxy
Environment=
RestrictAddressFamilies=AF_UNIX AF_LOCAL AF_NETLINK AF_QIPCRTR
Restart=on-failure
RestartSec=5s
